// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/hwameistor/datastore/pkg/apis/client/clientset/versioned/scheme"
	v1alpha1 "github.com/hwameistor/datastore/pkg/apis/datastore/v1alpha1"
	rest "k8s.io/client-go/rest"
)

type DatastoreV1alpha1Interface interface {
	RESTClient() rest.Interface
	StorageBackendsGetter
}

// DatastoreV1alpha1Client is used to interact with features provided by the datastore.io group.
type DatastoreV1alpha1Client struct {
	restClient rest.Interface
}

func (c *DatastoreV1alpha1Client) StorageBackends() StorageBackendInterface {
	return newStorageBackends(c)
}

// NewForConfig creates a new DatastoreV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*DatastoreV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &DatastoreV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new DatastoreV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *DatastoreV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new DatastoreV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *DatastoreV1alpha1Client {
	return &DatastoreV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *DatastoreV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
