apiVersion: datastore.io/v1alpha1
kind: DataLoadRequest
metadata:
  name: minio-llm
spec:
  type: minio
  node: k8s-node1
  minio:
    endpoint: 127.0.0.1:9000
    bucket: llm
    secretAccessKey: 6nTHn4ujDp0SRc3rKoPC0CpoDdZLLveYg8eimcKJ
    accessKeyId: AvyEJhLGWTnp4KvU18bM
