apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-dataload
  namespace: default
spec:
  serviceName: nginx-dataload
  replicas: 1
  selector:
    matchLabels:
      app: nginx-dataload
  template:
    metadata:
      labels:
        app: nginx-dataload
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      initContainers:
        - name: init-dataload
          image: docker.io/candy199808/hwameistor:datamanager_v052001
          args:
            - --trainingdataConfigName=test
          securityContext:
            privileged: true
          env:
            - name: POD_UUID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      containers:
        - name: nginx
          image: docker.io/library/nginx:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - containerPort: 80
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hwameistor-dataset