apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dataloadrequests.datastore.io
spec:
  group: datastore.io
  names:
    kind: DataLoadRequest
    listKind: DataLoadRequestList
    plural: dataloadrequests
    shortNames:
    - dlr
    singular: dataloadrequest
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.dataSource
      name: DataSource
      type: string
    - jsonPath: .spec.subDir
      name: SubDir
      type: string
    - jsonPath: .spec.retry
      name: Retry
      type: boolean
    - jsonPath: .spec.retryInterval
      name: RetryInterval
      priority: 1
      type: integer
    - jsonPath: .status.phase
      name: Phase
      type: string
    - jsonPath: .status.retryCount
      name: RetryCount
      priority: 1
      type: integer
    - jsonPath: .status.loadingStartTime
      name: LoadingStartTime
      type: date
    - jsonPath: .status.loadingCompleteTime
      name: LoadingCompleteTime
      type: date
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .status.error
      name: Error
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: DataLoadRequest is the Schema for the dataloadrequests API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: DataLoadRequestSpec defines the desired state of DataLoadRequest
            properties:
              dataSource:
                description: name of the data source
                type: string
              isGlobal:
                description: indicate if the request is for all or not
                type: boolean
              node:
                description: name of the node who will loads the data, and it works
                  only when isglobal is false
                type: string
              retry:
                default: false
                type: boolean
              retryInterval:
                default: 1
                format: int64
                type: integer
              subDir:
                type: string
            required:
            - dataSource
            - isGlobal
            - node
            - retry
            - retryInterval
            type: object
          status:
            description: DataLoadRequestStatus defines the observed state of DataLoadRequest
            properties:
              error:
                type: string
              loadingCompleteTime:
                format: date-time
                type: string
              loadingStartTime:
                format: date-time
                type: string
              phase:
                enum:
                - Preparing
                - Loading
                - Completed
                - Failed
                type: string
              retryCount:
                default: 0
                format: int64
                type: integer
            required:
            - retryCount
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
