apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: storagebackends.datastore.io
spec:
  group: datastore.io
  names:
    kind: StorageBackend
    listKind: StorageBackendList
    plural: storagebackends
    singular: storagebackend
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: StorageBackend is the Schema for the storagebackends API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: StorageBackendSpec defines the desired state of StorageBackend
            type: object
          status:
            description: StorageBackendStatus defines the observed state of StorageBackend
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
