// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/hwameistor/datastore/pkg/apis/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// DataLoadRequests returns a DataLoadRequestInformer.
	DataLoadRequests() DataLoadRequestInformer
	// StorageBackends returns a StorageBackendInformer.
	StorageBackends() StorageBackendInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// DataLoadRequests returns a DataLoadRequestInformer.
func (v *version) DataLoadRequests() DataLoadRequestInformer {
	return &dataLoadRequestInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// StorageBackends returns a StorageBackendInformer.
func (v *version) StorageBackends() StorageBackendInformer {
	return &storageBackendInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
