// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hwameistor/datastore/pkg/apis/datastore/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDataLoadRequests implements DataLoadRequestInterface
type FakeDataLoadRequests struct {
	Fake *FakeDatastoreV1alpha1
}

var dataloadrequestsResource = schema.GroupVersionResource{Group: "datastore.io", Version: "v1alpha1", Resource: "dataloadrequests"}

var dataloadrequestsKind = schema.GroupVersionKind{Group: "datastore.io", Version: "v1alpha1", Kind: "DataLoadRequest"}

// Get takes name of the dataLoadRequest, and returns the corresponding dataLoadRequest object, and an error if there is any.
func (c *FakeDataLoadRequests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DataLoadRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(dataloadrequestsResource, name), &v1alpha1.DataLoadRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataLoadRequest), err
}

// List takes label and field selectors, and returns the list of DataLoadRequests that match those selectors.
func (c *FakeDataLoadRequests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DataLoadRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(dataloadrequestsResource, dataloadrequestsKind, opts), &v1alpha1.DataLoadRequestList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DataLoadRequestList{ListMeta: obj.(*v1alpha1.DataLoadRequestList).ListMeta}
	for _, item := range obj.(*v1alpha1.DataLoadRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dataLoadRequests.
func (c *FakeDataLoadRequests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(dataloadrequestsResource, opts))
}

// Create takes the representation of a dataLoadRequest and creates it.  Returns the server's representation of the dataLoadRequest, and an error, if there is any.
func (c *FakeDataLoadRequests) Create(ctx context.Context, dataLoadRequest *v1alpha1.DataLoadRequest, opts v1.CreateOptions) (result *v1alpha1.DataLoadRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(dataloadrequestsResource, dataLoadRequest), &v1alpha1.DataLoadRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataLoadRequest), err
}

// Update takes the representation of a dataLoadRequest and updates it. Returns the server's representation of the dataLoadRequest, and an error, if there is any.
func (c *FakeDataLoadRequests) Update(ctx context.Context, dataLoadRequest *v1alpha1.DataLoadRequest, opts v1.UpdateOptions) (result *v1alpha1.DataLoadRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(dataloadrequestsResource, dataLoadRequest), &v1alpha1.DataLoadRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataLoadRequest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDataLoadRequests) UpdateStatus(ctx context.Context, dataLoadRequest *v1alpha1.DataLoadRequest, opts v1.UpdateOptions) (*v1alpha1.DataLoadRequest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(dataloadrequestsResource, "status", dataLoadRequest), &v1alpha1.DataLoadRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataLoadRequest), err
}

// Delete takes name of the dataLoadRequest and deletes it. Returns an error if one occurs.
func (c *FakeDataLoadRequests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(dataloadrequestsResource, name), &v1alpha1.DataLoadRequest{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDataLoadRequests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(dataloadrequestsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DataLoadRequestList{})
	return err
}

// Patch applies the patch and returns the patched dataLoadRequest.
func (c *FakeDataLoadRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DataLoadRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(dataloadrequestsResource, name, pt, data, subresources...), &v1alpha1.DataLoadRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataLoadRequest), err
}
