// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hwameistor/datastore/pkg/apis/datastore/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStorageBackends implements StorageBackendInterface
type FakeStorageBackends struct {
	Fake *FakeDatastoreV1alpha1
}

var storagebackendsResource = schema.GroupVersionResource{Group: "datastore.io", Version: "v1alpha1", Resource: "storagebackends"}

var storagebackendsKind = schema.GroupVersionKind{Group: "datastore.io", Version: "v1alpha1", Kind: "StorageBackend"}

// Get takes name of the storageBackend, and returns the corresponding storageBackend object, and an error if there is any.
func (c *FakeStorageBackends) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.StorageBackend, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(storagebackendsResource, name), &v1alpha1.StorageBackend{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageBackend), err
}

// List takes label and field selectors, and returns the list of StorageBackends that match those selectors.
func (c *FakeStorageBackends) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.StorageBackendList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(storagebackendsResource, storagebackendsKind, opts), &v1alpha1.StorageBackendList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.StorageBackendList{ListMeta: obj.(*v1alpha1.StorageBackendList).ListMeta}
	for _, item := range obj.(*v1alpha1.StorageBackendList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested storageBackends.
func (c *FakeStorageBackends) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(storagebackendsResource, opts))
}

// Create takes the representation of a storageBackend and creates it.  Returns the server's representation of the storageBackend, and an error, if there is any.
func (c *FakeStorageBackends) Create(ctx context.Context, storageBackend *v1alpha1.StorageBackend, opts v1.CreateOptions) (result *v1alpha1.StorageBackend, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(storagebackendsResource, storageBackend), &v1alpha1.StorageBackend{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageBackend), err
}

// Update takes the representation of a storageBackend and updates it. Returns the server's representation of the storageBackend, and an error, if there is any.
func (c *FakeStorageBackends) Update(ctx context.Context, storageBackend *v1alpha1.StorageBackend, opts v1.UpdateOptions) (result *v1alpha1.StorageBackend, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(storagebackendsResource, storageBackend), &v1alpha1.StorageBackend{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageBackend), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeStorageBackends) UpdateStatus(ctx context.Context, storageBackend *v1alpha1.StorageBackend, opts v1.UpdateOptions) (*v1alpha1.StorageBackend, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(storagebackendsResource, "status", storageBackend), &v1alpha1.StorageBackend{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageBackend), err
}

// Delete takes name of the storageBackend and deletes it. Returns an error if one occurs.
func (c *FakeStorageBackends) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(storagebackendsResource, name), &v1alpha1.StorageBackend{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStorageBackends) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(storagebackendsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.StorageBackendList{})
	return err
}

// Patch applies the patch and returns the patched storageBackend.
func (c *FakeStorageBackends) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.StorageBackend, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(storagebackendsResource, name, pt, data, subresources...), &v1alpha1.StorageBackend{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageBackend), err
}
