// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/hwameistor/datastore/pkg/apis/client/clientset/versioned/typed/datastore/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeDatastoreV1alpha1 struct {
	*testing.Fake
}

func (c *FakeDatastoreV1alpha1) DataLoadRequests() v1alpha1.DataLoadRequestInterface {
	return &FakeDataLoadRequests{c}
}

func (c *FakeDatastoreV1alpha1) StorageBackends() v1alpha1.StorageBackendInterface {
	return &FakeStorageBackends{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeDatastoreV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
