apiVersion: v1
kind: Pod
metadata:
  name: llm-trainer
spec:
  containers:
  - image: busybox
    name: trainer
    args:
      - tail -f /dev/null
    volumeMounts:
    - name: data
      mountPath: /llm/data
    - name: checkpoints
      mountPath: /llm/checkpoints
    - name: models
      mountPath: /llm/models
  - name: sidecar-dataloader
    image: lsun7927/dataloader:v001
    args:
      - --nodename=$(NODENAME)
      - --targetDir=/llm/data
      - --checkpointsDir=/llm/checkpoints
      #- --modelsDir=/llm/models
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: NODENAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.nodeName
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
    volumeMounts:
    - name: data
      mountPath: /llm/data
    - name: checkpoints
      mountPath: /llm/checkpoints
    - name: models
      mountPath: /llm/models
  volumes:
  - name: data
    emptyDir: {}
  - name: checkpoints
    emptyDir: {}
  - name: models
    emptyDir: {}

