// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/hwameistor/datastore/pkg/apis/datastore/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// StorageBackendLister helps list StorageBackends.
type StorageBackendLister interface {
	// List lists all StorageBackends in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.StorageBackend, err error)
	// Get retrieves the StorageBackend from the index for a given name.
	Get(name string) (*v1alpha1.StorageBackend, error)
	StorageBackendListerExpansion
}

// storageBackendLister implements the StorageBackendLister interface.
type storageBackendLister struct {
	indexer cache.Indexer
}

// NewStorageBackendLister returns a new StorageBackendLister.
func NewStorageBackendLister(indexer cache.Indexer) StorageBackendLister {
	return &storageBackendLister{indexer: indexer}
}

// List lists all StorageBackends in the indexer.
func (s *storageBackendLister) List(selector labels.Selector) (ret []*v1alpha1.StorageBackend, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.StorageBackend))
	})
	return ret, err
}

// Get retrieves the StorageBackend from the index for a given name.
func (s *storageBackendLister) Get(name string) (*v1alpha1.StorageBackend, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("storagebackend"), name)
	}
	return obj.(*v1alpha1.StorageBackend), nil
}
