//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataLoadRequest) DeepCopyInto(out *DataLoadRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataLoadRequest.
func (in *DataLoadRequest) DeepCopy() *DataLoadRequest {
	if in == nil {
		return nil
	}
	out := new(DataLoadRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataLoadRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataLoadRequestList) DeepCopyInto(out *DataLoadRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataLoadRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataLoadRequestList.
func (in *DataLoadRequestList) DeepCopy() *DataLoadRequestList {
	if in == nil {
		return nil
	}
	out := new(DataLoadRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataLoadRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataLoadRequestSpec) DeepCopyInto(out *DataLoadRequestSpec) {
	*out = *in
	if in.MinIO != nil {
		in, out := &in.MinIO, &out.MinIO
		*out = new(MinIOSpec)
		**out = **in
	}
	if in.NFS != nil {
		in, out := &in.NFS, &out.NFS
		*out = new(NFSSpec)
		**out = **in
	}
	if in.FTP != nil {
		in, out := &in.FTP, &out.FTP
		*out = new(FTPSpec)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataLoadRequestSpec.
func (in *DataLoadRequestSpec) DeepCopy() *DataLoadRequestSpec {
	if in == nil {
		return nil
	}
	out := new(DataLoadRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataLoadRequestStatus) DeepCopyInto(out *DataLoadRequestStatus) {
	*out = *in
	in.LoadingStartTime.DeepCopyInto(&out.LoadingStartTime)
	in.LoadingCompleteTime.DeepCopyInto(&out.LoadingCompleteTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataLoadRequestStatus.
func (in *DataLoadRequestStatus) DeepCopy() *DataLoadRequestStatus {
	if in == nil {
		return nil
	}
	out := new(DataLoadRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FTPSpec) DeepCopyInto(out *FTPSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FTPSpec.
func (in *FTPSpec) DeepCopy() *FTPSpec {
	if in == nil {
		return nil
	}
	out := new(FTPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinIOSpec) DeepCopyInto(out *MinIOSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinIOSpec.
func (in *MinIOSpec) DeepCopy() *MinIOSpec {
	if in == nil {
		return nil
	}
	out := new(MinIOSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NFSSpec) DeepCopyInto(out *NFSSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NFSSpec.
func (in *NFSSpec) DeepCopy() *NFSSpec {
	if in == nil {
		return nil
	}
	out := new(NFSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackend) DeepCopyInto(out *StorageBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackend.
func (in *StorageBackend) DeepCopy() *StorageBackend {
	if in == nil {
		return nil
	}
	out := new(StorageBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackendList) DeepCopyInto(out *StorageBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackendList.
func (in *StorageBackendList) DeepCopy() *StorageBackendList {
	if in == nil {
		return nil
	}
	out := new(StorageBackendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackendSpec) DeepCopyInto(out *StorageBackendSpec) {
	*out = *in
	if in.MinIO != nil {
		in, out := &in.MinIO, &out.MinIO
		*out = new(MinIOSpec)
		**out = **in
	}
	if in.NFS != nil {
		in, out := &in.NFS, &out.NFS
		*out = new(NFSSpec)
		**out = **in
	}
	if in.FTP != nil {
		in, out := &in.FTP, &out.FTP
		*out = new(FTPSpec)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackendSpec.
func (in *StorageBackendSpec) DeepCopy() *StorageBackendSpec {
	if in == nil {
		return nil
	}
	out := new(StorageBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackendStatus) DeepCopyInto(out *StorageBackendStatus) {
	*out = *in
	if in.LastRefreshTimestamp != nil {
		in, out := &in.LastRefreshTimestamp, &out.LastRefreshTimestamp
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackendStatus.
func (in *StorageBackendStatus) DeepCopy() *StorageBackendStatus {
	if in == nil {
		return nil
	}
	out := new(StorageBackendStatus)
	in.DeepCopyInto(out)
	return out
}
