name: Period check
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  e2e-test:
    runs-on: ["vsphere"]
    timeout-minutes: 600
    steps:
      - name: delete
        run: |
          sudo rm -rf /github/actions-runner/_work/datastore/datastore/_build
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: e2e test
        env:
          E2E_TESTING_LEVEL: "periodCheck"
        run: make e2e-test
