name: HwameiStor PR

on:
  pull_request:
    branches:
      - main
    paths:
      - "pkg/**"
      - "test/**"

jobs:
  pr-test:
    runs-on: ["vsphere"]
    timeout-minutes: 180
    steps:
      - name: delete
        run: |
          sudo rm -rf rm -rf /github/actions-runner/_work/datastore/datastore/_build
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: pr test
        env:
          E2E_TESTING_LEVEL: "pr-e2e"
        run: make pr-test

